"""empty message

Revision ID: 8a5857db7f08
Revises: None
Create Date: 2016-11-17 20:49:34.828552

"""

# revision identifiers, used by Alembic.
revision = '8a5857db7f08'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('enclosure', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'enclosure')
    ### end Alembic commands ###
