"""empty message

Revision ID: d90e76ab5dc6
Revises: 8a5857db7f08
Create Date: 2016-11-17 21:19:02.040264

"""

# revision identifiers, used by Alembic.
revision = 'd90e76ab5dc6'
down_revision = '8a5857db7f08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('ifenclosure', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ifenclosure')
    ### end Alembic commands ###
